[package]
name = "crabnets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
dyn-clone = "1.0.16"
itertools = "0.12.1"
regex = "1.10.3"
